data_ingestion:
  bucket_name: "my_bucket2689"
  bucket_file_name: "Hotel_Reservations.csv"
  train_ratio: 0.8

data_processing:
  categorical_features:
    - type_of_meal_plan
    - room_type_reserved
    - required_car_parking_space
    - repeated_guest
    - market_segment_type
    - booking_status
  
  numerical_features:
    - no_of_adults
    - no_of_children
    - no_of_weekend_nights
    - no_of_week_nights
    - lead_time
    - arrival_year
    - arrival_month 
    - arrival_date
    - avg_price_per_room
    - no_of_special_requests
    - no_of_previous_cancellations
    - no_of_previous_bookings_not_canceled
  
  skewness_threshold: 0.5
  num_of_features: 10   